//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestLatihanC1
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COM_CUSTOMER()
        {
            this.SALES_SO = new HashSet<SALES_SO>();
        }
    
        public int COM_CUSTOMER_ID { get; set; }
        public string CUSTOMER_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALES_SO> SALES_SO { get; set; }
    }
}
