//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestLatihanC1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_DEMOEntities : DbContext
    {
        public DB_DEMOEntities()
            : base("name=DB_DEMOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COM_CUSTOMER> COM_CUSTOMER { get; set; }
        public virtual DbSet<SALES_SO> SALES_SO { get; set; }
        public virtual DbSet<SALES_SO_LITEM> SALES_SO_LITEM { get; set; }
    }
}
