//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestLatihanC1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES_SO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SALES_SO()
        {
            this.SALES_SO_LITEM = new HashSet<SALES_SO_LITEM>();
        }
    
        public int SALES_SO_ID { get; set; }
        public string SO_NO { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public Nullable<int> COM_CUSTOMER_ID { get; set; }
        public string ADDRESS { get; set; }
    
        public virtual COM_CUSTOMER COM_CUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALES_SO_LITEM> SALES_SO_LITEM { get; set; }
    }
}
