//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestLatihanC1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES_SO_LITEM
    {
        public int SALES_SO_LITEM_ID { get; set; }
        public Nullable<int> SALES_SO_ID { get; set; }
        public string ITEM_NAME { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<double> PRICE { get; set; }
    
        public virtual SALES_SO SALES_SO { get; set; }
    }
}
